### ISSUE TITLE
Adding more blocklist sources

### ISSUE THREAD

**Issue by simcha-lgbt** [simcha-lgbt/simchadon#10]
### Pitch

Currently thanks to merged [PR 25691](https://github.com/mastodon/mastodon/pull/25691) that was proposed for vanilla Mastodon, the setup script prompts for blocklist importing. Currently it gives two options: Oliphant's T0 and the bad space's lists. We should add the Simcha Block List and [Seirdy's Pleroma List](https://seirdy.one/posts/2023/05/02/fediverse-blocklists/) as options too

### Motivation

Because only having these two as options is extremely limiting

**Comment by sgrigson** [comment]
And another option is Gardenfence, which includes Blocklist reasons.

https://gardenfence.github.io/
